Magni/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from Myapp.views import home, ajax
# from myapp.views2 import AjaxableResponseMixin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home, name="home"),
    url(r'^ajax/$', ajax, name="ajax"),
    # url(r'^/mixin$', AjaxableResponseMixin, name="mixin"),


]

Myapp/models.py
from django.db import models


class Person(models.Model):

	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	middle_name = models.CharField(max_length=100, blank=True)
	telephone = models.CharField(max_length=100, blank=True)
	email = models.EmailField(max_length=100, blank=True)

	def __unicode__(self):
		return '%s %s' % (self.first_name, self.last_name)

 
class Location (models.Model):
	person = models.ForeignKey(Person,blank=True, null=True)
	region = models.CharField(max_length=50, blank=True)
	sity = models.CharField(max_length=50, blank=True)

	def __unicode__(self):
		return '%s, %s' % (self.region,self.sity)


class Comment(models.Model):
	person = models.ManyToManyField(Person)
	text = models.TextField(max_length=1000)
	
	def __unicode__(self):
		return unicode(self.id)

Myapp/forms.py
from django import forms
from .models import Location
region_choices = Location.objects.values_list('id','region').order_by().distinct()
print region_choices
class CommentForm(forms.Form):
	first_name = forms.CharField(max_length=100, required=True)
	last_name = forms.CharField(max_length=100, required=True)
	middle_name = forms.CharField(max_length=100, required=False)
	telephone = forms.CharField(max_length=100, required=False)
	email = forms.EmailField(max_length=100, required=False, widget=forms.EmailInput(attrs={'id': 'email-text'}))
	region = forms.CharField(required=False, widget=forms.Select(
		choices=region_choices, attrs={'id': 'id-region',})
	)

	sity = forms.CharField(required=False, widget=forms.Select(
		choices=[], attrs={'id': 'id-sity',})
	)

	def clean_first_name(self):
		first_name = self.cleaned_data.get('first_name')
		return first_name

	def clean_last_name(self):
		last_name = self.cleaned_data.get('last_name')
		return last_name

	def clean_middle_name(self):
		middle_name = self.cleaned_data.get('middle_name')
		return middle_name

	def clean_telephone(self):
		telephone = self.cleaned_data.get('telephone')
		return telephone

	def clean_email(self):
		email = self.cleaned_data.get('email')
		# email_base, provider = email.split("@")
		# domain, extension = provider.split('.')
		return email

	def clean_region(self):
		region = self.cleaned_data.get('region')
		return region

	def clean_sity(self):
		sity = self.cleaned_data.get('sity')
		return sity

Myapp/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
import json
from .forms import CommentForm
from .models import Person, Location, Comment



# sity_choices = Location.objects.values_list('id','sity').filter(region).order_by()

def home(request):
	if request.method == 'POST':
		form = CommentForm(request.POST)
		person = Person()
		if form.is_valid():
			# first_name = form.cleaned_data['first_name']
			# last_name = form.cleaned_data['last_name']
			# middle_name = form.cleaned_data['middle_name']
			# telephone = form.cleaned_data['telephone']
			# email = form.cleaned_data['email']
			# region = form.cleaned_data['region']
			# sity = form.cleaned_data['sity']
			# instance = form.save(commit=False)
			# first_name = person.first_name
			

			return HttpResponseRedirect("/admin")
	else:
		form = CommentForm()
	return render(request, "base.html", {'form':form})


def ajax(request):
    if request.method == 'POST':
        response_data = {}
        
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        middle_name = request.POST.get('middle_name')
        telephone = request.POST.get('telephone')
        email = request.POST.get('email')
        region = request.POST.get('region')
        sity = request.POST.get('sity')

        location = Location.objects.create(region=region,sity=sity)
        person = Person.objects.create(first_name=first_name, last_name=last_name, 
        	middle_name=middle_name,telephone = telephone, email=email)
        
        region_choices = ''
        
        response_data['result'] = 'Create  POST successful!'
        response_data['first_name'] = first_name
        response_data['last_name'] = last_name
        response_data['region'] = region_choices
        response_data['sity'] = sity
        response_data['email-text'] = email
       
        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )

Myapp/templates/base.html
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="http://bootstrap-3.ru/assets/ico/favicon.ico">

    <title>Magnitest</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fluid" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Magnitest</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/admin">Admin</a></li>
            <li><a href="{% url 'ajax' %}">Comment</a></li>
            <li><a href="">test</a></li>          
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
{% block content %}

      <div class="row">
        <div class="col-sm-4 ">    
            <form method='POST' action='' id ="post-form">{% csrf_token %}
            {{ form.as_p }}
            <input class='btn btn-primary' type='submit' value='Sign Up' />
            </form>
        </div>
      </div>
    </div><!-- /.container -->
{% if title %}
{{ title}}
{% endif %}

{% endblock %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <script type="text/javascript"> 
    $(document).ready(function(){
      
      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
              // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                    }
              }
        }
        return cookieValue;
      };



      function create_post() {
        var csrftoken = getCookie('csrftoken');
        var form_data = {
                 csrfmiddlewaretoken : csrftoken,
                 first_name : $('#id_first_name').val(),
                 middle_name : $('#id_middle_name').val(),
                 last_name : $('#id_last_name').val(),
                 telephone : $('#id_telephone').val(),
                 email : $('#email-text').val(),
                 region : $('#id-region').val(),
                 sity : $('#id-sity').val(),
        };

       /* var form_data = $(this).serialize();*/

        $.ajax({
        url : "{% url 'ajax' %}",
        type : "POST", 
        data : form_data,
        dataType: 'json',
        success : function(json) {
            console.log(json); // log the returned json to the console
            alert("Success!");
           
        },
        error : function(xhr,errmsg,err) {
            $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
        });
      };

      /*function set_sity(){
         var sity = {
                 sity : $('#id-sity').val(),
      }*/


      /*function change_sity() {
        var region = $(this).serialize();
        $.ajax({
        url : "{% url 'ajax' %}",
        type : "POST", 
        data : region,
        dataType: 'json',
        success : function(json) {
            console.log(json); // log the returned json to the console
            console.log("success"); // another sanity check
            alert("Region change!");
        },
        error : function(xhr,errmsg,err) {
            $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
        });
      };*/




    
    $('#post-form').on('submit', function(event){
        event.preventDefault();
        create_post();
    });

    $('#id-region').on('change', function(){
    /*    alert(this.value);*/
      console.log($('#id-region').text());
    });


    });
    </script>
      
</body></html>

Myapp/templates/comment.html
{% extends "base.html" %}

{% block content %}

{{ title }}

{% endblock %}